name: Build and Deploy IoT-Fault-Prediction

on:
  push:
    branches:
      - main  # or master, depending on your repo
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # <-- GitHub secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # <-- GitHub secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/iot-fault-prediction:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/iot-fault-prediction:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Deploy on Abarvan server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}       # <-- GitHub secret
          username: ${{ secrets.SERVER_USER }} # <-- GitHub secret
          key: ${{ secrets.SERVER_SSH_KEY }}   # <-- GitHub secret
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/iot-fault-prediction:latest
            docker stop iot-fault || true
            docker rm iot-fault || true
            docker run -d -p 8000:8000 --name iot-fault ${{ secrets.DOCKERHUB_USERNAME }}/iot-fault-prediction:latest
